### ISSUE TITLE
why would you want pressure to be `any`? 

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-analysis#5]
https://github.com/gSulpizio/isotherm-analysis/blob/1013b45d10287ad30288894708536716ff55f85d/src/modelFunctions.ts#L19

**Comment by gSulpizio** [comment]
I don't. Why can't it be any tho? I was mostly trying to understand

**Comment by kjappelbaum** [comment]
what error did it throw?

**Comment by gSulpizio** [comment]
probably it was another error as it now works, sorry!
